import type { AuditRecord } from "./audit-types";

export const MOCK_AUDIT_RECORDS: AuditRecord[] = [
  {
    id: "8ba40634-e649-47fb-9e23-a11a8f933da1",
    createdAt: "2026-07-30T08:47:52.000Z",
    completedAt: "2026-07-30T08:47:54.430Z",
    status: "success",
    httpStatus: 200,
    description: "Овсяная каша на молоке, банан, мёд и грецкие орехи.",
    photoCount: 2,
    photos: [
      {
        name: "IMG_3921.jpg",
        mimeType: "image/jpeg",
        size: 1_258_291,
      },
      {
        name: "IMG_3922.jpg",
        mimeType: "image/jpeg",
        size: 987_104,
      },
    ],
    response: {
      foods: [
        {
          name: "Овсяная каша на молоке",
          portionGrams: 260,
          carbsPer100g: 17.2,
          totalCarbs: 44.7,
          breadUnits: 3.7,
          confidence: "medium",
          note: "Масса оценена по объёму миски.",
        },
        {
          name: "Банан",
          portionGrams: 80,
          carbsPer100g: 23,
          totalCarbs: 18.4,
          breadUnits: 1.5,
          confidence: "high",
          note: "Примерно половина среднего банана.",
        },
      ],
      totalCarbs: 63.1,
      totalBreadUnits: 5.3,
      confidence: "medium",
      summary: "Овсяная каша с бананом, мёдом и орехами — около 5,3 ХЕ.",
      assumptions: [
        "Каша приготовлена без добавленного сахара.",
        "Количество мёда оценено по фотографии.",
      ],
      model: "gemini-3.6-flash",
    },
    totalCarbs: 63.1,
    totalBreadUnits: 5.3,
    model: "gemini-3.6-flash",
    durationMs: 2_430,
  },
  {
    id: "7cb85a7f-3fba-4a7a-9c93-8fafef1a715e",
    createdAt: "2026-07-30T07:41:12.000Z",
    completedAt: "2026-07-30T07:41:12.420Z",
    status: "error",
    httpStatus: 415,
    description: "Обед: плов с курицей.",
    photoCount: 1,
    photos: [
      {
        name: "meal.bmp",
        mimeType: "image/bmp",
        size: 2_180_440,
      },
    ],
    error: {
      code: "UNSUPPORTED_IMAGE",
      message: "Поддерживаются JPG, PNG, WebP, HEIC и HEIF.",
    },
    errorCode: "UNSUPPORTED_IMAGE",
    durationMs: 420,
  },
  {
    id: "559352a1-e7bb-41fc-a8b8-d3323448a615",
    createdAt: "2026-07-29T17:18:45.000Z",
    completedAt: "2026-07-29T17:18:46.810Z",
    status: "success",
    httpStatus: 200,
    description: "Творог 5% с клубникой.",
    photoCount: 0,
    photos: [],
    response: {
      foods: [
        {
          name: "Творог 5%",
          portionGrams: 180,
          carbsPer100g: 3,
          totalCarbs: 5.4,
          breadUnits: 0.5,
          confidence: "medium",
          note: "Принята стандартная порция.",
        },
        {
          name: "Клубника",
          portionGrams: 100,
          carbsPer100g: 7.7,
          totalCarbs: 7.7,
          breadUnits: 0.6,
          confidence: "medium",
          note: "Количество указано приблизительно.",
        },
      ],
      totalCarbs: 13.1,
      totalBreadUnits: 1.1,
      confidence: "medium",
      summary: "Творог с клубникой — около 1,1 ХЕ.",
      assumptions: ["В творог не добавлен сахар."],
      model: "gemini-3.6-flash",
    },
    totalCarbs: 13.1,
    totalBreadUnits: 1.1,
    model: "gemini-3.6-flash",
    durationMs: 1_810,
  },
];
